export const STRINGS = {
  today: 'Today',
  nothingOnCalendar: 'Nothing on the calendar today',
  allDone: 'All done!',
  allDoneForNow: 'All done for now!',
  addWeatherEntity: 'Add a weather entity to show forecast',
  dressingTipHeavyCoat: 'Heavy coat + hat',
  dressingTipCoatScarf: 'Coat + scarf',
  dressingTipLightJacket: 'Light jacket',
  dressingTipTShirt: 'T-shirt',
  dressingTipShorts: 'Shorts weather',
  dressingTipBoots: 'Boots + heavy coat',
  dressingTipUmbrella: ' + umbrella',
  dressingTipDefault: 'Check the weather',
  tasksTitle: 'Tasks',
  timePillNow: 'now',
  timePillInMinutes: (m: number) => `in ${m}m`,
  timePillInHours: (h: number) => `in ${h}h`,
  timePillTomorrow: (time: string) => `tomorrow ${time}`,
  errorUnavailable: '—',
  noRoutinesToday: 'no routines today',
  familyReady: (n: number, m: number) => `${n}/${m} ready`,
} as const;
